
[subjects, num_sub] = streams_util_subjectstring(2:28, {'s06', 's09'});

indepvars = {'perplexity'};
datadir   = '/project/3011044.02/preproc/meg/';
savedir   = '/project/3011044.02/analysis/freqanalysis/subject';


%% SUBJECT AND VARIABLE LOOP

for i = 1:numel(indepvars)

    indepvar = indepvars{i};

    for k = 1:numel(subjects)

        subject = subjects{k};
        inputargs = {'indepvar', indepvar, ...
                     'freqband', 'high-gamma', ...
                     'prune', 0, ...
                     'word_selection', 'all', ...
                     'doconfound', 1, ...
                     'removeonset', 0, ...
                     'savedir', savedir, ...
                     'datadir', datadir, ...
                     'shift', [0 200 400 600]};
        
        qsubfeval('streams_freqanalysis_contrast', subject, inputargs, ...
                                                            'memreq', 1024^3 * 12,...
                                                            'timreq', 45*60, ...
                                                            'matlabcmd', 'matlab2016b');
    end

end
    